### ISSUE TITLE
After updating to Obsidian v1.2.7, AQS stopped working

### ISSUE THREAD

**Issue by leterhaar** [tadashi-aikawa/obsidian-another-quick-switcher#166]
Console logs:

```
Command failed to execute:  obsidian-another-quick-switcher:search-command_recent-search
app.js:1 TypeError: Cannot read properties of undefined (reading 'instance')
    at AppHelper.getStarredFilePaths (plugin:obsidian-another-quick-switcher:1812:59)
    at AnotherQuickSwitcherModal.indexingItems (plugin:obsidian-another-quick-switcher:2477:22)
    at new AnotherQuickSwitcherModal (plugin:obsidian-another-quick-switcher:2405:10)
    at showSearchDialog (plugin:obsidian-another-quick-switcher:3907:17)
    at Object.callback (plugin:obsidian-another-quick-switcher:4000:11)
    at bU (app.js:1:1677780)
    at e.executeCommand (app.js:1:1679216)
    at e.onTrigger (app.js:1:1093798)
    at e.handleKey (app.js:1:1007319)
    at e.handleKey (app.js:1:1007432)
```

Think it has to do w/ starred file paths being phased out as of this release (`AppHelper.getStarredFilePaths` seems to be the culprit). Thanks for looking in to this and apologies if this is not an issue, but just has to to with my outdated plugin or lack of Obsidian skills :)

**Comment by tadashi-aikawa** [comment]
Hi, @leterhaar :)

Unfortunately, I couldn't reproduce it. Could you tell me the reproduction steps in the sandbox vault? (AQS version is v8.9.2)

**Comment by tadashi-aikawa** [comment]
I’m glad to hear that!
